import { NextRequest, NextResponse } from 'next/server';
import { createBrowserClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { Document, Packer, Paragraph, TextRun } from 'docx';

export const maxDuration = 60;
export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    const cookieStore = cookies();
    const supabase = createBrowserClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() { return cookieStore.getAll(); },
          setAll(cookiesToSet) {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options)
            );
          },
        },
      }
    );

    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { text, fileName = 'transcription', format = 'docx' } = await request.json();

    if (!text) {
      return NextResponse.json({ error: 'No text provided' }, { status: 400 });
    }

    if (format === 'docx') {
      const paragraphs: Paragraph[] = [];
      const textLines = text.split('\n');

      for (const line of textLines) {
        if (line.startsWith('#')) {
          const content = line.replace(/^#+\s*/, '');
          paragraphs.push(
            new Paragraph({
              children: [new TextRun({ text: content, bold: true, size: 24 })],
              spacing: { before: 200, after: 100 },
            })
          );
        } else if (line.startsWith('- ') || line.startsWith('* ')) {
          paragraphs.push(
            new Paragraph({
              children: [new TextRun({ text: line.substring(2) })],
              bullet: { level: 0 },
            })
          );
        } else if (line.trim() === '') {
          paragraphs.push(new Paragraph({ children: [new TextRun({ text: '' })] }));
        } else {
          paragraphs.push(
            new Paragraph({
              children: [new TextRun({ text: line, size: 20 })],
              spacing: { after: 60 },
            })
          );
        }
      }

      const doc = new Document({
        title: fileName,
        description: 'Generated by Source2Txt',
        sections: [{ children: paragraphs }],
      });

      const buffer = await Packer.toBuffer(doc);
      const uint8array = new Uint8Array(buffer);

      return new NextResponse(uint8array, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'Content-Disposition': `attachment; filename="${fileName.replace(/\.[^/.]+$/, '')}.docx"`,
        },
      });
    }

    return NextResponse.json({ error: 'Unsupported format' }, { status: 400 });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}