const express = require('express');
const { Document, Packer, Paragraph, TextRun } = require('docx');
const { getUserFromToken } = require('../lib/supabase');

const router = express.Router();

router.post('/', async (req, res) => {
  try {
    const auth = await getUserFromToken(req);
    if (!auth) return res.status(401).json({ error: 'Unauthorized' });

    const { text, fileName = 'transcription', format = 'docx' } = req.body;
    if (!text) return res.status(400).json({ error: 'No text provided' });

    if (format === 'docx') {
      const paragraphs = [];
      const textLines = text.split('\n');

      for (const line of textLines) {
        if (line.startsWith('#')) {
          const content = line.replace(/^#+\s*/, '');
          paragraphs.push(new Paragraph({
            children: [new TextRun({ text: content, bold: true, size: 24 })],
            spacing: { before: 200, after: 100 },
          }));
        } else if (line.startsWith('- ') || line.startsWith('* ')) {
          paragraphs.push(new Paragraph({
            children: [new TextRun({ text: line.substring(2) })],
            bullet: { level: 0 },
          }));
        } else if (line.trim() === '') {
          paragraphs.push(new Paragraph({ children: [new TextRun({ text: '' })] }));
        } else {
          paragraphs.push(new Paragraph({
            children: [new TextRun({ text: line, size: 20 })],
            spacing: { after: 60 },
          }));
        }
      }

      const doc = new Document({
        title: fileName,
        description: 'Generated by Source2Txt',
        sections: [{ children: paragraphs }],
      });

      const buffer = await Packer.toBuffer(doc);

      res.set({
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${fileName.replace(/\.[^/.]+$/, '')}.docx"`,
      });
      res.send(Buffer.from(buffer));
    } else {
      res.status(400).json({ error: 'Unsupported format' });
    }
  } catch (error) {
    console.error('Export error:', error);
    res.status(500).json({ error: 'Export failed' });
  }
});

module.exports = router;
